"""empty message

Revision ID: 2c8c9e005b1d
Revises: 
Create Date: 2024-04-03 19:57:44.295522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8c9e005b1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=9000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_types_name'), ['name'], unique=True)

    op.create_table('genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genders_name'), ['name'], unique=True)

    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_types_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('part_name', sa.String(length=255), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['user_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('user_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_types_name'))

    op.drop_table('user_types')
    with op.batch_alter_table('genders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genders_name'))

    op.drop_table('genders')
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_types_name'))

    op.drop_table('document_types')
    op.drop_table('document')
    # ### end Alembic commands ###
