"""empty message

Revision ID: 3b82c2f70e28
Revises: 2c8c9e005b1d
Create Date: 2024-04-04 00:29:34.133595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b82c2f70e28'
down_revision = '2c8c9e005b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patr_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.drop_column('part_name')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('part_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('password_hash')
        batch_op.drop_column('patr_name')

    # ### end Alembic commands ###
