"""empty message

Revision ID: f5e20fe90321
Revises: d52f13635f1e
Create Date: 2024-04-04 07:49:40.065676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5e20fe90321'
down_revision = 'd52f13635f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastName', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('firstName', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('patrName', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.Integer(), nullable=True))
        batch_op.drop_constraint('users_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'genders', ['sex'], ['id'])
        batch_op.drop_column('patr_name')
        batch_op.drop_column('gender_id')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('gender_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('patr_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_ibfk_1', 'genders', ['gender_id'], ['id'])
        batch_op.drop_column('sex')
        batch_op.drop_column('patrName')
        batch_op.drop_column('firstName')
        batch_op.drop_column('lastName')

    # ### end Alembic commands ###
